version: '3.8'

services:
  test:
    build:
      dockerfile: Dockerfile.test
      context: .
      args:
        - 'HTTP_PROXY'
        - 'HTTPS_PROXY'
    depends_on:
      - cache
    command: test

  cache:
    image: 'blackglory/cache:0.6.0'
